name: Build Tag

on:
  push:
    tags:
      - v**

jobs:
  Build-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - uses: pnpm/action-setup@v2.1.0
        name: Install pnpm
        with:
          version: 7.12.2
          run_install: true

      - name: Install
        run: pnpm run build

      - name: Publish
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
